tinyMCE.addI18n('sk.emotions_dlg',{
title:"Vlo\u017Ei\u0165 emotikonu",
desc:"Emotikony",
cool:"Namakan\u00FD",
cry:"Pla\u010De",
embarassed:"Zahamben\u00FD",
foot_in_mouth:"Top\u00E1nka v \u00FAstach",
frown:"Frown",
innocent:"Nevinn\u00FD",
kiss:"Bozk",
laughing:"\u00DAsmev",
money_mouth:"Koruny",
sealed:"Zape\u010Daten\u00FD",
smile:"\u00DAsmev",
surprised:"Prekvapen\u00FD",
tongue_out:"Vyplazen\u00FD jazyk",
undecided:"Neroshodn\u00FD",
wink:"\u017Dmurk",
yell:"Kri\u010Da\u0165"
});