tinyMCE.addI18n('tr.advlink_dlg',{
title:"Link ekle/d\u00FCzenle",
url:"Link URL",
target:"Hedef",
titlefield:"Ba\u015Fl\u0131k",
is_email:"Girmi\u015F oldu\u011Funuz link bir email adresine benziyor, gerekli mailto: \u00F6nekinin eklenmesini ister misiniz?",
is_external:"Girmi\u015F oldu\u011Funuz URL harici bir linke benziyor, gerekli http:// \u00F6nekinin eklenmesini ister misiniz?",
list:"Link listesi",
general_tab:"Genel",
popup_tab:"Popup",
events_tab:"Olaylar",
advanced_tab:"Geli\u015Fmi\u015F",
general_props:"Genel \u00F6zellikler",
popup_props:"Popup \u00F6zellikler",
event_props:"Olaylar",
advanced_props:"Geli\u015Fmi\u015F \u00F6zellikler",
popup_opts:"Se\u00E7enekler",
anchor_names:"Ba\u011Flant\u0131lar",
target_same:"Bu pencere/frame de a\u00E7",
target_parent:"\u00DCst pencere/frame de a\u00E7",
target_top:"En \u00FCst frame de a\u00E7 (t\u00FCm frame leri de\u011Fi\u015Ftirir)",
target_blank:"Yeni pencerede a\u00E7",
popup:"Javascript popup",
popup_url:"Popup URL",
popup_name:"Pencere ad\u0131",
popup_return:"Insert 'return false'",
popup_scrollbars:"Show scrollbars",
popup_statusbar:"Show status bar",
popup_toolbar:"Show toolbars",
popup_menubar:"Show menu bar",
popup_location:"Show location bar",
popup_resizable:"Make window resizable",
popup_dependent:"Dependent (Mozilla/Firefox only)",
popup_size:"Size",
popup_position:"Position (X/Y)",
id:"Id",
style:"Style",
classes:"Classes",
target_name:"Hedef name",
langdir:"Language direction",
target_langcode:"Hedef language",
langcode:"Language code",
encoding:"Hedef character encoding",
mime:"Hedef MIME type",
rel:"Relationship page to target",
rev:"Relationship target to page",
tabindex:"Tabindex",
accesskey:"Accesskey",
ltr:"Soldan sa\u011Fa",
rtl:"Sa\u011Fdan sola",
link_list:"Link list"
});