tinyMCE.addI18n('tr.xhtmlxtras_dlg',{
attribute_label_title:"Ba\u015Fl\u0131k",
attribute_label_id:"ID",
attribute_label_class:"Class",
attribute_label_style:"Style",
attribute_label_cite:"Cite",
attribute_label_datetime:"Date/Time",
attribute_label_langdir:"Text Direction",
attribute_option_ltr:"Soldan sa\u011Fa",
attribute_option_rtl:"Sa\u011Fdan sola",
attribute_label_langcode:"Language",
attribute_label_tabindex:"TabIndex",
attribute_label_accesskey:"AccessKey",
attribute_events_tab:"Olaylar",
attribute_attrib_tab:"Attributes",
general_tab:"Genel",
attrib_tab:"Attributes",
events_tab:"Olaylar",
fieldset_general_tab:"Genel Settings",
fieldset_attrib_tab:"Element Attributes",
fieldset_events_tab:"Element Olaylar",
title_ins_element:"Insertion Element",
title_del_element:"Deletion Element",
title_acronym_element:"Acronym Element",
title_abbr_element:"Abbreviation Element",
title_cite_element:"Citation Element",
remove:"Remove",
insert_date:"Insert current date/time",
option_ltr:"Soldan sa\u011Fa",
option_rtl:"Sa\u011Fdan sola",
attribs_title:"Insert/Edit Attributes"
});