tinyMCE.addI18n('tr.fullpage_dlg',{
title:"Document properties",
meta_tab:"Genel",
appearance_tab:"Appearance",
advanced_tab:"Geli\u015Fmi\u015F",
meta_props:"Meta information",
langprops:"Language and encoding",
meta_title:"Ba\u015Fl\u0131k",
meta_keywords:"Keywords",
meta_description:"Description",
meta_robots:"Robots",
doctypes:"Doctype",
langcode:"Language code",
langdir:"Language direction",
ltr:"Soldan sa\u011Fa",
rtl:"Sa\u011Fdan sola",
xml_pi:"XML declaration",
encoding:"Character encoding",
appearance_bgprops:"Background \u00F6zellikler",
appearance_marginprops:"Body margins",
appearance_linkprops:"Link colors",
appearance_textprops:"Text \u00F6zellikler",
bgcolor:"Background color",
bgimage:"Background image",
left_margin:"Sol margin",
right_margin:"Sa\u011F margin",
top_margin:"\u00DCst margin",
bottom_margin:"Alt margin",
text_color:"Text color",
font_size:"Yaz\u0131 tipi b\u00FCy\u00FCkl\u00FC\u011F\u00FC",
font_face:"Yaz\u0131 tipi face",
link_color:"Link color",
hover_color:"Hover color",
visited_color:"Visited color",
active_color:"Active color",
textcolor:"Color",
fontsize:"Yaz\u0131 tipi b\u00FCy\u00FCkl\u00FC\u011F\u00FC",
fontface:"Yaz\u0131 tipi ailesi",
meta_index_follow:"Index and follow the links",
meta_index_nofollow:"Index and don't follow the links",
meta_noindex_follow:"Do not index but follow the links",
meta_noindex_nofollow:"Do not index and don\'t follow the links",
appearance_style:"Stylesheet and style \u00F6zellikleri",
stylesheet:"Stylesheet",
style:"Style",
author:"Author",
copyright:"Copyright",
add:"Add new element",
remove:"Remove selected element",
moveup:"Move selected element up",
movedown:"Move selected element down",
head_elements:"Head elements",
info:"Information",
add_title:"Ba\u015Fl\u0131k element",
add_meta:"Meta element",
add_script:"Script element",
add_style:"Style element",
add_link:"Link element",
add_base:"Base element",
add_comment:"Comment node",
title_element:"Ba\u015Fl\u0131k element",
script_element:"Script element",
style_element:"Style element",
base_element:"Base element",
link_element:"Link element",
meta_element:"Meta element",
comment_element:"Comment",
src:"Src",
language:"Language",
href:"Href",
target:"Hedef",
type:"Type",
charset:"Charset",
defer:"Defer",
media:"Media",
properties:"Properties",
name:"Name",
value:"Value",
content:"Content",
rel:"Rel",
rev:"Rev",
hreflang:"Href lang",
general_props:"Genel",
advanced_props:"Geli\u015Fmi\u015F"
});