tinyMCE.addI18n('zh.media_dlg',{
title:" \r\n\u63D2\u5165/\u7F16\u8F91\u5D4C\u5165\u5A92\u4F53 \r\n",
general:" \r\n\u4E00\u822C \r\n",
advanced:" \r\n\u9AD8\u7EA7 \r\n",
file:" \r\n\u6587\u4EF6/\u7F51\u5740 \r\n",
list:" \r\n\u6E05\u5355 \r\n",
size:" \r\n\u5C3A\u5BF8 \r\n",
preview:" \r\n\u9884\u89C8 \r\n",
constrain_proportions:" \r\n\u4FDD\u6301\u6BD4\u4F8B \r\n",
type:" \r\n\u7C7B\u578B \r\n",
id:" \r\nId \r\n",
name:" \r\n\u540D\u79F0 \r\n",
class_name:" \r\n\u7C7B\u578B \r\n",
vspace:" \r\n\u7EB5\u5411\u95F4\u8DDD \r\n",
hspace:" \r\n\u6C34\u51C6\u95F4\u8DDD \r\n",
play:" \r\n\u81EA\u52A8\u64AD\u653E \r\n",
loop:" \r\n\u56DE\u5708 \r\n",
menu:" \r\n\u663E\u793A\u9009\u5355 \r\n",
quality:" \r\n\u54C1\u8D28 \r\n",
scale:" \r\n\u6BD4\u4F8B \r\n",
align:" \r\n\u5BF9\u9F50 \r\n",
salign:" \r\nSAlign \r\n",
wmode:" \r\nWMode \r\n",
bgcolor:" \r\n\u80CC\u666F\u8272 \r\n",
base:" \r\n\u57FA\u5E95 \r\n",
flashvars:" \r\nFlashvars \r\n",
liveconnect:" \r\nSWLiveConnect \r\n",
autohref:" \r\nAutoHREF \r\n",
cache:" \r\n\u5FEB\u53D6\u8BB0\u5FC6\u4F53 \r\n",
hidden:" \r\n\u9690\u85CF \r\n",
controller:" \r\n\u63A7\u5236\u9762\u677F \r\n",
kioskmode:" \r\nKiosk\u6A21\u5F0F \r\n",
playeveryframe:" \r\nPlay every frame \r\n",
targetcache:" \r\n\u76EE\u6807\u7F13\u5B58 \r\n",
correction:" \r\nNo correction \r\n",
enablejavascript:" \r\n\u542F\u7528JavaScript \r\n",
starttime:" \r\n\u5F00\u59CB\u65F6\u95F4 \r\n",
endtime:" \r\n\u7ED3\u675F\u65F6\u95F4 \r\n",
href:" \r\nHref \r\n",
qtsrcchokespeed:" \r\nChoke speed \r\n",
target:" \r\n\u76EE\u6807 \r\n",
volume:" \r\n\u97F3\u91CF \r\n",
autostart:" \r\n\u81EA\u52A8\u5F00\u59CB \r\n",
enabled:" \r\n\u542F\u7528 \r\n",
fullscreen:" \r\n\u5168\u8424\u5E55 \r\n",
invokeurls:" \r\n\u76F8\u5173URLs \r\n",
mute:" \r\n\u9759\u97F3 \r\n",
stretchtofit:" \r\n\u62C9\u4F38 \r\n",
windowlessvideo:" \r\n\u65E0\u8FB9\u6846 \r\n",
balance:" \r\n\u5E73\u8861 \r\n",
baseurl:" \r\n\u57FA\u51C6URL \r\n",
captioningid:" \r\nCaptioning id \r\n",
currentmarker:" \r\nCurrent marker \r\n",
currentposition:" \r\nCurrent position \r\n",
defaultframe:" \r\nDefault frame \r\n",
playcount:" \r\nPlay count \r\n",
rate:" \r\nRate \r\n",
uimode:" \r\nUI Mode \r\n",
flash_options:" \r\nFlash\u9009\u9879 \r\n",
qt_options:" \r\nQuicktime\u9009\u9879 \r\n",
wmp_options:" \r\nWindows media player\u9009\u9879 \r\n",
rmp_options:" \r\nReal media player\u9009\u9879 \r\n",
shockwave_options:" \r\nShockwave\u9009\u9879 \r\n",
autogotourl:" \r\nAuto goto URL \r\n",
center:" \r\nCenter \r\n",
imagestatus:" \r\nImage status \r\n",
maintainaspect:" \r\nMaintain aspect \r\n",
nojava:" \r\nNo java \r\n",
prefetch:" \r\nPrefetch \r\n",
shuffle:" \r\nShuffle \r\n",
console:" \r\nConsole \r\n",
numloop:" \r\nNum loops \r\n",
controls:" \r\nControls \r\n",
scriptcallbacks:" \r\nScript callbacks \r\n",
swstretchstyle:" \r\nStretch style \r\n",
swstretchhalign:" \r\nStretch H-Align \r\n",
swstretchvalign:" \r\nStretch V-Align \r\n",
sound:" \r\nSound \r\n",
progress:" \r\nProgress \r\n",
qtsrc:" \r\nQT Src \r\n",
qt_stream_warn:" \r\nStreamed rtsp resources should be added to the QT Src field under the advanced tab.\nYou should also add a non streamed version to the Src field.. \r\n",
align_top:" \r\n\u4E0A\u65B9 \r\n",
align_right:" \r\n\u9760\u53F3 \r\n",
align_bottom:" \r\n\u4E0B\u65B9 \r\n",
align_left:" \r\n\u9760\u5DE6 \r\n",
align_center:" \r\nCenter \r\n",
align_top_left:" \r\nTop left \r\n",
align_top_right:" \r\nTop right \r\n",
align_bottom_left:" \r\nBottom left \r\n",
align_bottom_right:" \r\nBottom right \r\n",
flv_options:" \r\nFlash video options \r\n",
flv_scalemode:" \r\nScale mode \r\n",
flv_buffer:" \r\nBuffer \r\n",
flv_startimage:" \r\nStart image \r\n",
flv_starttime:" \r\nStart time \r\n",
flv_defaultvolume:" \r\nDefault volumne \r\n",
flv_hiddengui:" \r\nHidden GUI \r\n",
flv_autostart:" \r\nAuto start \r\n",
flv_loop:" \r\nLoop \r\n",
flv_showscalemodes:" \r\nShow scale modes \r\n",
flv_smoothvideo:" \r\nSmooth video \r\n",
flv_jscallback:" \r\nJS Callback \r\n"
});