tinyMCE.addI18n('tr.advanced_dlg',{
about_title:"TinyMCE hakk\u0131nda",
about_general:"Hakk\u0131nda",
about_help:"Yard\u0131m",
about_license:"Lisans",
about_plugins:"Plugins",
about_plugin:"Plugin",
about_author:"Yazar",
about_version:"Version",
about_loaded:"Y\u00FCkl\u00FC pluginker",
anchor_title:"Ba\u011Flant\u0131 ekle/d\u00FCzenle",
anchor_name:"Ba\u011Flant\u0131 ad\u0131",
code_title:"HTML Kod Edit\u00F6r\u00FC",
code_wordwrap:"S\u00F6zc\u00FCk kayd\u0131rma",
colorpicker_title:"Bir renk se\u00E7iniz",
colorpicker_picker_tab:"Se\u00E7ici",
colorpicker_picker_title:"Renk se\u00E7ici",
colorpicker_palette_tab:"Palet",
colorpicker_palette_title:"Palet renkleri",
colorpicker_named_tab:"\u0130simlendirilmi\u015F",
colorpicker_named_title:"\u0130simlendirilmi\u015F renkler",
colorpicker_color:"Renk:",
colorpicker_name:"\u0130sim:",
charmap_title:"\u00D6zel karakter se\u00E7iniz",
image_title:"Resim ekle/d\u00FCzenle",
image_src:"Resim URL",
image_alt:"Resim tan\u0131m\u0131",
image_list:"Resim listesi",
image_border:"Kenar",
image_dimensions:"Boyutlar",
image_vspace:"Dikey alan",
image_hspace:"Yatay alan",
image_align:"Hiza",
image_align_baseline:"Taban",
image_align_top:"\u00DCst",
image_align_middle:"Orta",
image_align_bottom:"Alt",
image_align_texttop:"Yaz\u0131 \u00FCst\u00FC",
image_align_textbottom:"Yaz\u0131 alt\u0131",
image_align_left:"Sol",
image_align_right:"Sa\u011F",
link_title:"Link ekle/d\u00FCzenle",
link_url:"Link URL",
link_target:"Hedef",
link_target_same:"Linki ayn\u0131 pencerede a\u00E7",
link_target_blank:"Linki yeni bir pencerede a\u00E7",
link_titlefield:"Ba\u015Fl\u0131k",
link_is_email:"Girmi\u015F oldu\u011Funuz link bir email adresine benziyor, gerekli mailto: \u00F6nekinin eklenmesini ister misiniz?",
link_is_external:"Girmi\u015F oldu\u011Funuz URL harici bir linke benziyor, gerekli http:// \u00F6nekinin eklenmesini ister misiniz?",
link_list:"Link listesi"
});