#!/bin/sh

if [ "x${1}" = "x" ]; then
	echo "usage: makedist [dist-X.X]"
	exit 1
fi
mkdir $1

cp -r change_log.txt COPYING.lib libs makedist NEWS plugins README $1
vi $1/README $1/libs/SmartyValidate.class.php
find $1 -name \.svn -exec rm -rf {} \;
tar -zcvf ${1}.tar.gz $1
zip -r ${1}.zip $1
rm -rf $1
